<a href="https://colab.research.google.com/github/Requireding/AI-Research-Paper-Intelligence-System/blob/main/AI_Research_Paper_Intelligence_System.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install datasets

In [ ]:
from datasets import load_dataset

In [ ]:
dataset = load_dataset("CShorten/ML-ArXiv-Papers",split = 'train')

README.md:   0%|          | 0.00/986 [00:00<?, ?B/s]

ML-Arxiv-Papers.csv:   0%|          | 0.00/147M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/117592 [00:00<?, ? examples/s]

In [ ]:
print(dataset)

Dataset({
    features: ['Unnamed: 0.1', 'Unnamed: 0', 'title', 'abstract'],
    num_rows: 117592
})


In [ ]:
dataset[0]

{'Unnamed: 0.1': 0,
 'Unnamed: 0': 0.0,
 'title': 'Learning from compressed observations',
 'abstract': '  The problem of statistical learning is to construct a predictor of a random\nvariable $Y$ as a function of a related random variable $X$ on the basis of an\ni.i.d. training sample from the joint distribution of $(X,Y)$. Allowable\npredictors are drawn from some specified class, and the goal is to approach\nasymptotically the performance (expected loss) of the best predictor in the\nclass. We consider the setting in which one has perfect observation of the\n$X$-part of the sample, while the $Y$-part has to be communicated at some\nfinite bit rate. The encoding of the $Y$-values is allowed to depend on the\n$X$-values. Under suitable regularity conditions on the admissible predictors,\nthe underlying family of probability distributions and the loss function, we\ngive an information-theoretic characterization of achievable predictor\nperformance in terms of conditional distortion-rat

In [ ]:
import pandas as pd

In [ ]:
import pandas as pd
from datasets import load_dataset
dataset = load_dataset("CShorten/ML-ArXiv-Papers",split = 'train')

df = pd.DataFrame(dataset)
df = df[['title', 'abstract']].copy()
display(df.head())

,title,abstract
0,Learning from compressed observations,The problem of statistical learning is to co...
1,Sensor Networks with Random Links: Topology De...,"In a sensor network, in practice, the commun..."
2,The on-line shortest path problem under partia...,The on-line shortest path problem is conside...
3,A neural network approach to ordinal regression,Ordinal regression is an important type of l...
4,Parametric Learning and Monte Carlo Optimization,This paper uncovers and explores the close r...


In [ ]:
df = pd.DataFrame(dataset)
df

,Unnamed: 0.1,Unnamed: 0,title,abstract
0,0,0.0,Learning from compressed observations,The problem of statistical learning is to co...
1,1,1.0,Sensor Networks with Random Links: Topology De...,"In a sensor network, in practice, the commun..."
2,2,2.0,The on-line shortest path problem under partia...,The on-line shortest path problem is conside...
3,3,3.0,A neural network approach to ordinal regression,Ordinal regression is an important type of l...
4,4,4.0,Parametric Learning and Monte Carlo Optimization,This paper uncovers and explores the close r...
...,...,...,...,...
117587,4995,NaN,Detecting COVID-19 Conspiracy Theories with Tr...,The sharing of fake news and conspiracy theori...
117588,4996,NaN,Fair Feature Subset Selection using Multiobjec...,The feature subset selection problem aims at s...
117589,4997,NaN,A Simple Duality Proof for Wasserstein Distrib...,We present a short and elementary proof of the...
117590,4998,NaN,Combined Learning of Neural Network Weights fo...,"We introduce CoLN, Combined Learning of Neural..."


In [ ]:
df.columns

Index(['Unnamed: 0.1', 'Unnamed: 0', 'title', 'abstract'], dtype='object')

In [ ]:
df

,Unnamed: 0.1,Unnamed: 0,title,abstract
0,0,0.0,Learning from compressed observations,The problem of statistical learning is to co...
1,1,1.0,Sensor Networks with Random Links: Topology De...,"In a sensor network, in practice, the commun..."
2,2,2.0,The on-line shortest path problem under partia...,The on-line shortest path problem is conside...
3,3,3.0,A neural network approach to ordinal regression,Ordinal regression is an important type of l...
4,4,4.0,Parametric Learning and Monte Carlo Optimization,This paper uncovers and explores the close r...
...,...,...,...,...
117587,4995,NaN,Detecting COVID-19 Conspiracy Theories with Tr...,The sharing of fake news and conspiracy theori...
117588,4996,NaN,Fair Feature Subset Selection using Multiobjec...,The feature subset selection problem aims at s...
117589,4997,NaN,A Simple Duality Proof for Wasserstein Distrib...,We present a short and elementary proof of the...
117590,4998,NaN,Combined Learning of Neural Network Weights fo...,"We introduce CoLN, Combined Learning of Neural..."


In [ ]:
df.shape

(117592, 4)

In [ ]:
df.head()

,Unnamed: 0.1,Unnamed: 0,title,abstract
0,0,0.0,Learning from compressed observations,The problem of statistical learning is to co...
1,1,1.0,Sensor Networks with Random Links: Topology De...,"In a sensor network, in practice, the commun..."
2,2,2.0,The on-line shortest path problem under partia...,The on-line shortest path problem is conside...
3,3,3.0,A neural network approach to ordinal regression,Ordinal regression is an important type of l...
4,4,4.0,Parametric Learning and Monte Carlo Optimization,This paper uncovers and explores the close r...


In [ ]:
df.shape

(117592, 4)

In [ ]:
df.isnull().sum()

,0
Unnamed: 0.1,0
Unnamed: 0,5000
title,0
abstract,0


In [ ]:
df["paper_text"] = df["title"] + "" + df["abstract"]

In [ ]:
df[["paper_text"]].head()

,paper_text
0,Learning from compressed observations The pro...
1,Sensor Networks with Random Links: Topology De...
2,The on-line shortest path problem under partia...
3,A neural network approach to ordinal regressio...
4,Parametric Learning and Monte Carlo Optimizati...


In [ ]:
type(df["paper_text"])

pandas.core.series.Series

In [ ]:
print(df["paper_text"].iloc[0])

Learning from compressed observations  The problem of statistical learning is to construct a predictor of a random
variable $Y$ as a function of a related random variable $X$ on the basis of an
i.i.d. training sample from the joint distribution of $(X,Y)$. Allowable
predictors are drawn from some specified class, and the goal is to approach
asymptotically the performance (expected loss) of the best predictor in the
class. We consider the setting in which one has perfect observation of the
$X$-part of the sample, while the $Y$-part has to be communicated at some
finite bit rate. The encoding of the $Y$-values is allowed to depend on the
$X$-values. Under suitable regularity conditions on the admissible predictors,
the underlying family of probability distributions and the loss function, we
give an information-theoretic characterization of achievable predictor
performance in terms of conditional distortion-rate functions. The ideas are
illustrated on the example of nonparametric regressi

In [ ]:
from sentence_transformers import SentenceTransformer

In [ ]:
model = SentenceTransformer("all-MiniLM-L6-v2")

modules.json:   0%|          | 0.00/349 [00:00<?, ?B/s]

config_sentence_transformers.json:   0%|          | 0.00/116 [00:00<?, ?B/s]

README.md:   0%|          | 0.00/10.5k [00:00<?, ?B/s]

sentence_bert_config.json:   0%|          | 0.00/53.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/612 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/90.9M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

tokenizer_config.json:   0%|          | 0.00/350 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/112 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/190 [00:00<?, ?B/s]

In [ ]:
print(type(model))

<class 'sentence_transformers.sentence_transformer.model.SentenceTransformer'>


In [ ]:
sample_text=df["paper_text"].iloc[0]
sample_text

'Learning from compressed observations  The problem of statistical learning is to construct a predictor of a random\nvariable $Y$ as a function of a related random variable $X$ on the basis of an\ni.i.d. training sample from the joint distribution of $(X,Y)$. Allowable\npredictors are drawn from some specified class, and the goal is to approach\nasymptotically the performance (expected loss) of the best predictor in the\nclass. We consider the setting in which one has perfect observation of the\n$X$-part of the sample, while the $Y$-part has to be communicated at some\nfinite bit rate. The encoding of the $Y$-values is allowed to depend on the\n$X$-values. Under suitable regularity conditions on the admissible predictors,\nthe underlying family of probability distributions and the loss function, we\ngive an information-theoretic characterization of achievable predictor\nperformance in terms of conditional distortion-rate functions. The ideas are\nillustrated on the example of nonparame

In [ ]:
df["paper_text"] = df["paper_text"].fillna("").astype(str)
df["paper_text"] = df["paper_text"].str.replace("\n"," ",regex=False)
df["paper_text"] = df["paper_text"].str.strip()

In [ ]:
embedding =model.encode(sample_text)
print(type(embedding))
print(embedding.shape)

<class 'numpy.ndarray'>
(384,)


In [ ]:
embedding[:56]

array([-0.13156408, -0.00678268, -0.00367609,  0.03265162,  0.11219638,
        0.01227266,  0.09816723, -0.09005228,  0.04231165, -0.0197735 ,
       -0.03308417,  0.07452939,  0.10632038, -0.0206043 , -0.02052102,
        0.00169492,  0.07081947,  0.05854449, -0.1123191 ,  0.02082469,
        0.05692545,  0.0201578 ,  0.025831  ,  0.03217029,  0.10513768,
       -0.0967676 ,  0.02700802, -0.0234509 , -0.04549679, -0.01013698,
       -0.01794855, -0.04814427,  0.01077653, -0.03759069,  0.01943478,
        0.0371519 ,  0.02967843,  0.04330944,  0.04373208,  0.03704866,
       -0.00182593,  0.00455186, -0.00799067,  0.03037373, -0.014378  ,
        0.0379515 ,  0.05959161, -0.02583361, -0.0652157 ,  0.05900266,
       -0.02107138,  0.07359428, -0.05720108,  0.0029406 ,  0.00767515,
       -0.03334165], dtype=float32)

In [ ]:
sample_embedding=model.encode(df["paper_text"].head(5).tolist())

In [ ]:
print(sample_embedding.shape)

(5, 384)


In [ ]:
import sklearn
from sklearn.metrics.pairwise import cosine_similarity

In [ ]:
for i in range(1, 5):
    sim = cosine_similarity(sample_embedding[0].reshape(1, -1), sample_embedding[i].reshape(1, -1))
    print(f"Similarity with Paper {i}: {sim[0][0]}")

Similarity with Paper 1: 0.36625272035598755
Similarity with Paper 2: 0.33522841334342957
Similarity with Paper 3: 0.15505117177963257
Similarity with Paper 4: 0.37421536445617676


In [ ]:
import os
import numpy as np
if os.path.exists("paper_embeddings.npy"):
  embeddings = np.load("paper_embeddings.npy")
else:
  print("Generating embeddings")
  embeddings = model.encode(df["paper_text"].tolist(),batch_size=32,show_progress_bar=True)
  np.save("paper_embeddings.npy",embeddings)
  print("Embeddings saved")

Generating embeddings


Batches:   0%|          | 0/3675 [00:00<?, ?it/s]

Embeddings saved


In [ ]:
print("Cleaned DataFrame saved successfully!")

Cleaned DataFrame saved successfully!


In [ ]:
query = "deep learning for medical image analysis"
query_emb = model.encode([query])

In [ ]:
similarities = cosine_similarity(query_emb, sample_embedding)

print("Similarity scores for the first 5 papers:\n", similarities)

Similarity scores for the first 5 papers:
 [[0.14026166 0.01298691 0.07622992 0.24243265 0.17442404]]


In [ ]:
!pip install faiss-cpu

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 18.5/18.5 MB 46.8 MB/s eta 0:00:00


In [ ]:
import faiss
import numpy as np

In [ ]:
papers_to_encode = df["paper_text"].tolist()[:50000]

In [ ]:
print("Encoding 50,000 papers (Watch the green bar below)...")
all_embeddings = model.encode(papers_to_encode, show_progress_bar=True)

Encoding 50,000 papers (Watch the green bar below)...


Batches:   0%|          | 0/1563 [00:00<?, ?it/s]

In [ ]:
faiss_embeddings = np.array(all_embeddings).astype('float32')
faiss.normalize_L2(faiss_embeddings)

In [ ]:
index = faiss.IndexFlatIP(384)
index.add(faiss_embeddings)

In [ ]:
query_embedding = model.encode([query]).astype('float32')
faiss.normalize_L2(query_embedding)

k = 5 # Number of top results we want
distances, indices = index.search(query_embedding, k)

print("\n--- Search Results ---")
print("Top 5 distances:", distances)
print("Top 5 dataframe indices:", indices)


--- Search Results ---
Top 5 distances: [[0.7254224  0.71706605 0.7123305  0.6807246  0.67988193]]
Top 5 dataframe indices: [[26063 37161 18030 10466 29766]]


In [ ]:
print("\nTop Matching Papers:")
for i in indices[0]:
    print("-", df.iloc[i]['title'])


Top Matching Papers:
- An overview of deep learning in medical imaging focusing on MRI
- Medical Imaging with Deep Learning: MIDL 2019 -- Extended Abstract Track
- Deep learning in radiology: an overview of the concepts and a survey of
  the state of the art
- A Perspective on Deep Imaging
- Deep Learning in Cardiology


In [ ]:
import faiss

In [ ]:
faiss.normalize_L2(embedding.reshape(1, -1))

In [ ]:
index=faiss.IndexFlatIP(384)

In [ ]:
index.add(embedding.reshape(1, -1))

In [ ]:
import faiss

# Re-create the index using the already available faiss_embeddings (which contain 50,000 items)
# This addresses the issue where the index was re-initialized in a subsequent cell,
# ensuring it holds 50,000 items before printing ntotal.
index = faiss.IndexFlatIP(faiss_embeddings.shape[1]) # Use the dimension from faiss_embeddings
index.add(faiss_embeddings)
print(index.ntotal)

50000


In [ ]:
query="deep learning for medical image analysis"
query_embedding=model.encode([query])
query_embedding.shape

(1, 384)

In [ ]:
query_embedding = model.encode([query])
query_embedding = model.encode(query).reshape(1,-1)
print(query_embedding.shape)
print(query_embedding)

(1, 384)
[[-3.52527387e-02  5.43267019e-02  5.65811507e-02 -4.97096479e-02
  -3.52174975e-02 -2.67349035e-02 -8.23493954e-03  1.52610159e-02
  -1.31555321e-02 -5.45782410e-02 -5.26164807e-02 -1.20118028e-02
  -8.10011253e-02  9.73842591e-02 -1.15813069e-01 -1.68416537e-02
  -9.74306241e-02 -5.52441785e-03 -1.06863745e-01  7.64729595e-03
  -4.89180312e-02 -6.45615812e-03 -3.65177207e-02  2.23113392e-02
   5.65222166e-02  4.34987759e-03  6.29341602e-02 -1.09062947e-01
   3.48554738e-02 -1.03746457e-02  7.24759698e-02 -3.63332964e-02
   1.78153720e-02  1.52815403e-02  4.68112119e-02  7.27786496e-02
  -1.72747299e-02  5.71634434e-02  6.73017651e-03  2.91875433e-02
   4.84563448e-02  5.15046604e-02  3.13239805e-02  5.97998276e-02
   8.63464028e-02 -1.21598062e-03  3.83907817e-02 -1.21436790e-02
   5.59613705e-02  9.04098004e-02 -1.46837765e-02  2.19263267e-02
  -7.75724128e-02  8.67380574e-02  3.64488959e-02 -1.94061687e-03
  -1.39827458e-02 -1.21371960e-02 -1.06874950e-01 -9.59567167e-03
 

In [ ]:
faiss.normalize_L2(query_embedding)
query_embedding

array([[-3.52527387e-02,  5.43267019e-02,  5.65811507e-02,
        -4.97096479e-02, -3.52174975e-02, -2.67349035e-02,
        -8.23493954e-03,  1.52610159e-02, -1.31555321e-02,
        -5.45782410e-02, -5.26164807e-02, -1.20118028e-02,
        -8.10011253e-02,  9.73842591e-02, -1.15813069e-01,
        -1.68416537e-02, -9.74306241e-02, -5.52441785e-03,
        -1.06863745e-01,  7.64729595e-03, -4.89180312e-02,
        -6.45615812e-03, -3.65177207e-02,  2.23113392e-02,
         5.65222166e-02,  4.34987759e-03,  6.29341602e-02,
        -1.09062947e-01,  3.48554738e-02, -1.03746457e-02,
         7.24759698e-02, -3.63332964e-02,  1.78153720e-02,
         1.52815403e-02,  4.68112119e-02,  7.27786496e-02,
        -1.72747299e-02,  5.71634434e-02,  6.73017651e-03,
         2.91875433e-02,  4.84563448e-02,  5.15046604e-02,
         3.13239805e-02,  5.97998276e-02,  8.63464028e-02,
        -1.21598062e-03,  3.83907817e-02, -1.21436790e-02,
         5.59613705e-02,  9.04098004e-02, -1.46837765e-0

In [ ]:
D,I=index.search(query_embedding,5)
print(D)
print(I)

[[0.7254224  0.71706605 0.7123305  0.6807246  0.67988193]]
[[26063 37161 18030 10466 29766]]


In [ ]:
print(df.iloc[25846]["title"])

Reinforcement Learning with A* and a Deep Heuristic


In [ ]:
print(df.iloc[25846]["abstract"])

  A* is a popular path-finding algorithm, but it can only be applied to those
domains where a good heuristic function is known. Inspired by recent methods
combining Deep Neural Networks (DNNs) and trees, this study demonstrates how to
train a heuristic represented by a DNN and combine it with A*. This new
algorithm which we call aleph-star can be used efficiently in domains where the
input to the heuristic could be processed by a neural network. We compare
aleph-star to N-Step Deep Q-Learning (DQN Mnih et al. 2013) in a driving
simulation with pixel-based input, and demonstrate significantly better
performance in this scenario.



In [ ]:
print(df.iloc[37567]["title"])

Style Conditioned Recommendations


In [ ]:
print(df.iloc[37567]["abstract"])

  We propose Style Conditioned Recommendations (SCR) and introduce style
injection as a method to diversify recommendations. We use Conditional
Variational Autoencoder (CVAE) architecture, where both the encoder and decoder
are conditioned on a user profile learned from item content data. This allows
us to apply style transfer methodologies to the task of recommendations, which
we refer to as injection. To enable style injection, user profiles are learned
to be interpretable such that they express users' propensities for specific
predefined styles. These are learned via label-propagation from a dataset of
item content, with limited labeled points. To perform injection, the condition
on the encoder is learned while the condition on the decoder is selected per
explicit feedback. Explicit feedback can be taken either from a user's response
to a style or interest quiz, or from item ratings. In the absence of explicit
feedback, the condition at the encoder is applied to the decoder. We show

In [ ]:
def search_paper(query,k=5):
  query_embedding=model.encode([query])
  faiss.normalize_L2(query_embedding)
  D,I=index.search(query_embedding,k)
  return D,I

In [ ]:
D, I=search_paper("deep learning for medical image analysis")
print(D)
print(I)

[[0.7254224  0.71706605 0.7123305  0.6807246  0.67988193]]
[[26063 37161 18030 10466 29766]]


In [ ]:
def search_paper(query, k=5):
  query_embedding = model.encode([query])
  faiss.normalize_L2(query_embedding)
  D, I = index.search(query_embedding, k)
  for score,idx  in zip(D[0],I[0]) :
    print("Similarity score",score)
    print("Title",df.iloc[idx]["title"])
    print("Abstract",df.iloc[idx]["abstract"][:500])
    print()
  return D, I

In [ ]:
search_paper("deep learning for medical image analysis")

Similarity score 0.7254224
Title An overview of deep learning in medical imaging focusing on MRI
Abstract   What has happened in machine learning lately, and what does it mean for the
future of medical image analysis? Machine learning has witnessed a tremendous
amount of attention over the last few years. The current boom started around
2009 when so-called deep artificial neural networks began outperforming other
established models on a number of important benchmarks. Deep neural networks
are now the state-of-the-art machine learning models across a variety of areas,
from image analysis to natural l

Similarity score 0.71706605
Title Medical Imaging with Deep Learning: MIDL 2019 -- Extended Abstract Track
Abstract   This compendium gathers all the accepted extended abstracts from the Second
International Conference on Medical Imaging with Deep Learning (MIDL 2019),
held in London, UK, 8-10 July 2019. Note that only accepted extended abstracts
are listed here, the Proceedings of the MID

(array([[0.7254224 , 0.71706605, 0.7123305 , 0.6807246 , 0.67988193]],
       dtype=float32),
 array([[26063, 37161, 18030, 10466, 29766]]))

In [ ]:
!pip install transformers==4.46.3

In [ ]:
import transformers
from transformers import pipeline
summarizer = pipeline(
    "summarization",
    model="facebook/bart-large-cnn"
)

The cache for model files in Transformers v4.22.0 has been updated. Migrating your old cache. This is a one-time only operation. You can interrupt this and resume the migration later on by calling `transformers.utils.move_cache()`.


0it [00:00, ?it/s]

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


config.json: 0.00B [00:00, ?B/s]

model.safetensors:   0%|          | 0.00/1.63G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/363 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

Hardware accelerator e.g. GPU is available in the environment, but no `device` argument is passed to the `Pipeline` object. Model will be on CPU.


In [ ]:
type(summarizer)

transformers.pipelines.text2text_generation.SummarizationPipeline

In [ ]:
import pandas as pd
from datasets import load_dataset

In [ ]:
# Ensure df is defined in case of a kernel restart or out-of-order execution
if 'df' not in locals():
    print("Initializing df...")
    dataset = load_dataset("CShorten/ML-ArXiv-Papers", split='train')
    df = pd.DataFrame(dataset)
    df = df[['title', 'abstract']].copy()
    df["paper_text"] = df["title"] + " " + df["abstract"]
    df["paper_text"] = df["paper_text"].fillna("").astype(str)
    df["paper_text"] = df["paper_text"].str.replace("\n"," ",regex=False)
    df["paper_text"] = df["paper_text"].str.strip()
    print("df initialized.")


Initializing df...
df initialized.


In [ ]:
summary = summarizer(df.iloc[15666]["abstract"],max_length=120,min_length=40)
print(summary)

[{'summary_text': 'Existing methods use predefined criteria to choose the representation of data. There is a lack of methods that elicit from the user what she has learned from the data. We construct a theoretical model where patterns can be input as knowledge to the system. This background knowledge is used to find a Maximum Entropy distribution of the data, after which the system provides the user data projections.'}]


In [ ]:
type(summary)

list

In [ ]:
type(summary[0])

dict

In [ ]:
type(summary)

list

In [ ]:
summary[0]["summary_text"]

'Existing methods use predefined criteria to choose the representation of data. There is a lack of methods that elicit from the user what she has learned from the data. We construct a theoretical model where patterns can be input as knowledge to the system. This background knowledge is used to find a Maximum Entropy distribution of the data, after which the system provides the user data projections.'

In [ ]:
from sentence_transformers import SentenceTransformer

In [ ]:
import faiss

In [ ]:
import numpy as np

In [ ]:
# Ensure 'paper_text' column exists and is cleaned
df["paper_text"] = df["title"] + " " + df["abstract"]
df["paper_text"] = df["paper_text"].fillna("").astype(str)
df["paper_text"] = df["paper_text"].str.replace("\n"," ",regex=False)
df["paper_text"] = df["paper_text"].str.strip()

In [ ]:
# Initialize the sentence transformer model
model = SentenceTransformer("all-MiniLM-L6-v2")

In [ ]:
# Prepare embeddings for FAISS index
papers_to_encode = df["paper_text"].tolist()[:15000] # Use only first 15000 papers as per previous context
all_embeddings = model.encode(papers_to_encode, show_progress_bar=False) # No progress bar in programmatic fix
faiss_embeddings = np.array(all_embeddings).astype('float32')
faiss.normalize_L2(faiss_embeddings)

In [ ]:
# Initialize and add embeddings to FAISS index
index = faiss.IndexFlatIP(faiss_embeddings.shape[1])
index.add(faiss_embeddings)

In [ ]:
def search_and_summarize(query,k=5):
  query_embedding=model.encode([query])
  faiss.normalize_L2(query_embedding)
  D,I=index.search(query_embedding,k)

  print("\n--- Search Results ---")
  print(f"Query: {query}")
  print("\nTop Matching Papers:")
  for score,idx  in zip(D[0],I[0]) :
    print(f"Similarity score: {score:.4f}") # Format score for readability
    print("Title:",df.iloc[idx]["title"])
    print("Abstract:",df.iloc[idx]["abstract"][:5000]) # Print first 5000 chars

    # Generate summary
    summary_output = summarizer(df.iloc[idx]["abstract"],max_length=120,min_length=40,do_sample=False)
    print("Summary:", summary_output[0]["summary_text"])
    print("-" * 30) # Separator for readability
  return D, I # Return distances and indices if needed elsewhere

In [ ]:
# Call the function
search_and_summarize("deep learning for medical image analysis", k=5)


--- Search Results ---
Query: deep learning for medical image analysis

Top Matching Papers:
Similarity score: 0.6807
Title: A Perspective on Deep Imaging
Abstract:   The combination of tomographic imaging and deep learning, or machine learning
in general, promises to empower not only image analysis but also image
reconstruction. The latter aspect is considered in this perspective article
with an emphasis on medical imaging to develop a new generation of image
reconstruction theories and techniques. This direction might lead to
intelligent utilization of domain knowledge from big data, innovative
approaches for image reconstruction, and superior performance in clinical and
preclinical applications. To realize the full impact of machine learning on
medical imaging, major challenges must be addressed.

Summary: The combination of tomographic imaging and deep learning, or machine learning, promises to empower not only image analysis but also image reconstructions. This direction might le

(array([[0.6807246 , 0.67092216, 0.6521999 , 0.62811756, 0.6131154 ]],
       dtype=float32),
 array([[10466, 13730, 11873, 12691, 11282]]))

In [ ]:
pip install keybert==0.8.5

In [ ]:
from keybert import KeyBERT
kw_model =KeyBERT(model)

In [ ]:
type(kw_model) #model = SentenceTransformer("all-MiniLM-L6-v2")

keybert._model.KeyBERT

In [ ]:
text=df.iloc[25846]["abstract"]
keywords = kw_model.extract_keywords(text)

In [ ]:
print(keywords)

[('heuristic', 0.3634), ('path', 0.3534), ('dqn', 0.3236), ('networks', 0.3151), ('learning', 0.3133)]


In [ ]:
print(type(keywords))

<class 'list'>


In [ ]:
print(type(keywords[0]))

<class 'tuple'>


In [ ]:
keywords=kw_model.extract_keywords(text, keyphrase_ngram_range=(1, 3), stop_words='english')

In [ ]:
print(keywords)

[('heuristic represented dnn', 0.5167), ('deep learning dqn', 0.5081), ('step deep learning', 0.4614), ('networks dnns trees', 0.4576), ('train heuristic', 0.4457)]


In [ ]:
finalkeyword=kw_model.extract_keywords(text, keyphrase_ngram_range=(1, 3), stop_words='english', highlight=True)
finalkeyword

is popular path finding algorithm but it can only be applied to those domains where good heuristic function is 
known Inspired by recent methods combining Deep Neural Networks DNNs and trees this study demonstrates how to train
heuristic represented by DNN and combine it with This new algorithm which we call aleph star can be used 
efficiently in domains where the input to the heuristic could be processed by neural network We compare aleph star 
to Step Deep Learning Mnih et al 2013 in driving simulation with pixel based input and demonstrate significantly 
better performance in this scenario

[('heuristic represented dnn', 0.5167),
 ('deep learning dqn', 0.5081),
 ('step deep learning', 0.4614),
 ('networks dnns trees', 0.4576),
 ('train heuristic', 0.4457)]